package com.mycompany.parcial1_reyesvaldezmarco_web_operaciones_9a;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the XML-WS Tools. XML-WS Tools 4.0.1 Generated
 * source version: 3.0
 *
 */
@WebService(name = "calcularIntensidad", targetNamespace = "http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcularIntensidad {

    /**
     *
     * @param resistencia
     * @param voltaje
     * @return returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcularIntensidad", targetNamespace = "http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/", className = "com.mycompany.parcial1_reyesvaldezmarco_web_operaciones_9a.CalcularIntensidad_Type")
    @ResponseWrapper(localName = "calcularIntensidadResponse", targetNamespace = "http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/", className = "com.mycompany.parcial1_reyesvaldezmarco_web_operaciones_9a.CalcularIntensidadResponse")
    @Action(input = "http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/calcularIntensidad/calcularIntensidadRequest", output = "http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/calcularIntensidad/calcularIntensidadResponse")
    public double calcularIntensidad(
            @WebParam(name = "voltaje", targetNamespace = "") double voltaje,
            @WebParam(name = "resistencia", targetNamespace = "") double resistencia);

}
