
package com.mycompany.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "recu_reyesValdez_web_operaciones_9a", targetNamespace = "http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/", wsdlLocation = "http://localhost:8080/parcial1_reyesvaldezMarco_web_operaciones_9a/recu_reyesValdez_web_operaciones_9a?wsdl")
public class RecuReyesValdezWebOperaciones9A_Service
    extends Service
{

    private static final URL RECUREYESVALDEZWEBOPERACIONES9A_WSDL_LOCATION;
    private static final WebServiceException RECUREYESVALDEZWEBOPERACIONES9A_EXCEPTION;
    private static final QName RECUREYESVALDEZWEBOPERACIONES9A_QNAME = new QName("http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/", "recu_reyesValdez_web_operaciones_9a");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/parcial1_reyesvaldezMarco_web_operaciones_9a/recu_reyesValdez_web_operaciones_9a?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECUREYESVALDEZWEBOPERACIONES9A_WSDL_LOCATION = url;
        RECUREYESVALDEZWEBOPERACIONES9A_EXCEPTION = e;
    }

    public RecuReyesValdezWebOperaciones9A_Service() {
        super(__getWsdlLocation(), RECUREYESVALDEZWEBOPERACIONES9A_QNAME);
    }

    public RecuReyesValdezWebOperaciones9A_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECUREYESVALDEZWEBOPERACIONES9A_QNAME, features);
    }

    public RecuReyesValdezWebOperaciones9A_Service(URL wsdlLocation) {
        super(wsdlLocation, RECUREYESVALDEZWEBOPERACIONES9A_QNAME);
    }

    public RecuReyesValdezWebOperaciones9A_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECUREYESVALDEZWEBOPERACIONES9A_QNAME, features);
    }

    public RecuReyesValdezWebOperaciones9A_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecuReyesValdezWebOperaciones9A_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecuReyesValdezWebOperaciones9A
     */
    @WebEndpoint(name = "recu_reyesValdez_web_operaciones_9aPort")
    public RecuReyesValdezWebOperaciones9A getRecuReyesValdezWebOperaciones9APort() {
        return super.getPort(new QName("http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/", "recu_reyesValdez_web_operaciones_9aPort"), RecuReyesValdezWebOperaciones9A.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecuReyesValdezWebOperaciones9A
     */
    @WebEndpoint(name = "recu_reyesValdez_web_operaciones_9aPort")
    public RecuReyesValdezWebOperaciones9A getRecuReyesValdezWebOperaciones9APort(WebServiceFeature... features) {
        return super.getPort(new QName("http://parcial1_reyesvaldezmarco_web_operaciones_9a.mycompany.com/", "recu_reyesValdez_web_operaciones_9aPort"), RecuReyesValdezWebOperaciones9A.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECUREYESVALDEZWEBOPERACIONES9A_EXCEPTION!= null) {
            throw RECUREYESVALDEZWEBOPERACIONES9A_EXCEPTION;
        }
        return RECUREYESVALDEZWEBOPERACIONES9A_WSDL_LOCATION;
    }

}
